### PR TITLE
Updated LSTM so that it works; generator rewrote

### PR DESCRIPTION
**Pull request by mekomlusa**

### CODE REVIEW

**Comment by melonskin** [comment]
not quite familiar with LSTM, could @chenshaw1995 take a look at it?

**Comment by mekomlusa** [comment]
> not quite familiar with LSTM, could @chenshaw1995 take a look at it?

Yeah I'm still in the learning phase as well, but can confirm that the code can be executed. I'll have to rewrite this later for further optimization.

**Comment by melonskin** [comment]
tenor

**Comment by mekomlusa** [comment]
**The code can be executed, but have no idea about the model performance yet**

**Pull request merged**
